name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install server dependencies
      run: npm ci

    - name: Install client dependencies
      run: cd client && npm ci

    - name: Build React client
      run: npm run build

    - name: Run basic health check test
      run: |
        # Start server in background
        npm start &
        SERVER_PID=$!
        
        # Wait for server to start
        sleep 10
        
        # Test health endpoint
        curl -f http://localhost:8080/api/health || exit 1
        
        # Kill server
        kill $SERVER_PID

    - name: Check for security vulnerabilities
      run: |
        npm audit --audit-level high
        cd client && npm audit --audit-level high
